[package]
name = "clapping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#build = "build.rs"

[dependencies]
clap = "3.2.17"
clap_complete = "3.2.4"

[build-dependencies]
clap = "3.2.17"
clap_complete = "3.2.4"
